version: "3.3"
services:
  ###############################################################################
  # NGINX
  ###############################################################################
  nginx:
    volumes:
      - ./config/nginx/etc/conf.d/dev.conf:/etc/nginx/conf.d/default.template
  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    build:
      context: ./services/authenticator
      dockerfile: dev.Dockerfile
    volumes:
      - ./services/authenticator:/usr/app
      - /usr/app/node_modules
    ports:
      - "$AUTHENTICATOR_DEBUG_PORT:9226"
  ###############################################################################
  # PDFGenerator
  ###############################################################################
  pdfgenerator:
    build:
      context: ./services/pdfgenerator
      dockerfile: dev.Dockerfile
    volumes:
      - ./services/pdfgenerator:/usr/app
      - /usr/app/node_modules
    ports:
      - "$PDFGENERATOR_DEBUG_PORT:9227"
  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    build:
      context: ./services/emailer
      dockerfile: dev.Dockerfile
    volumes:
      - ./services/emailer:/usr/app
      - /usr/app/node_modules
    ports:
      - "$EMAILER_DEBUG_PORT:9228"
  ###############################################################################
  # api
  ###############################################################################
  api:
    build:
      context: ./services/api
      dockerfile: dev.Dockerfile
    volumes:
      - ./services/api:/usr/app
      - /usr/app/node_modules
    ports:
      - "$API_DEBUG_PORT:9230"
  ###############################################################################
  # Frontend
  ###############################################################################
  frontend:
    build:
      context: ./webapps/landlord
      dockerfile: dev.Dockerfile
    volumes:
      - ./webapps/landlord:/usr/app
      - /usr/app/node_modules
      - /usr/app/public
