version: '3.3'
services:
###############################################################################
# MongoDB
###############################################################################
  mongo:
    logging:
      driver: 'syslog'
      options:
        tag: '{{.Name}}/{{.ID}}'
        syslog-facility: 'daemon'
        syslog-address: 'udp://localhost:$LOGSTASH_PORT'
    depends_on:
      - kibana
###############################################################################
# RabbitMQ
###############################################################################
  rabbitmq:
    logging:
      driver: 'syslog'
      options:
        tag: '{{.Name}}/{{.ID}}'
        syslog-facility: 'daemon'
        syslog-address: 'udp://localhost:$LOGSTASH_PORT'
    depends_on:
      - kibana
###############################################################################
# PDFGenerator
###############################################################################
  pdfgenerator:
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://localhost:$LOGSTASH_PORT'
        tag: '{{.Name}}/{{.ID}}'
    depends_on:
      - mongo
      - kibana
###############################################################################
# Emailer
###############################################################################
  emailer:
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://localhost:$LOGSTASH_PORT'
        tag: '{{.Name}}/{{.ID}}'
    depends_on:
      - mongo
      - pdfgenerator
      - kibana
###############################################################################
# Loca (Front/Back-end)
###############################################################################
  loca:
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://localhost:$LOGSTASH_PORT'
        tag: '{{.Name}}/{{.ID}}'
    depends_on:
      - mongo
      - emailer
      - kibana
