version: "3.3"
services:
 ###############################################################################
  # Mongo
  ###############################################################################
  mongo:
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
  ###############################################################################
  # NGINX
  ###############################################################################
  nginx:
    volumes:
      - ./config/nginx/etc/conf.d/dev.conf:/etc/nginx/conf.d/default.template
  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    build:
      context: .
      dockerfile: services/authenticator/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/authenticator:/usr/app/services/authenticator
      - /usr/app/node_modules
      - /usr/app/services/authenticator/node_modules
    ports:
      - "$AUTHENTICATOR_DEBUG_PORT:9226"
  ###############################################################################
  # PDFGenerator
  ###############################################################################
  pdfgenerator:
    build:
      context: .
      dockerfile: services/pdfgenerator/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/pdfgenerator:/usr/app/services/pdfgenerator
      - /usr/app/node_modules
      - /usr/app/services/pdfgenerator/node_modules
    ports:
      - "$PDFGENERATOR_DEBUG_PORT:9227"
  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    build:
      context: .
      dockerfile: services/emailer/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/emailer:/usr/app/services/emailer
      - /usr/app/node_modules
      - /usr/app/services/emailer/node_modules
    ports:
      - "$EMAILER_DEBUG_PORT:9228"
  ###############################################################################
  # api
  ###############################################################################
  api:
    build:
      context: .
      dockerfile: services/api/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/api:/usr/app/services/api
      - /usr/app/node_modules
      - /usr/app/services/api/node_modules
    ports:
      - "$API_DEBUG_PORT:9230"
  ###############################################################################
  # Frontend
  ###############################################################################
  frontend:
    build:
      context: .
      dockerfile: webapps/landlord/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./webapps/landlord:/usr/app/webapps/landlord
      - /usr/app/webapps/landlord/public
      - /usr/app/node_modules
      - /usr/app/webapps/landlord/node_modules
