version: '3.3'
services:
###############################################################################
# Redis
###############################################################################
  redis:
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
        tag: '{{.Name}}/{{.ID}}'
      #   syslog-facility: 'daemon'
    depends_on:
      - kibana
###############################################################################
# Mongo
###############################################################################
  mongo:
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
        tag: '{{.Name}}/{{.ID}}'
      #   syslog-facility: 'daemon'
    depends_on:
      - kibana
###############################################################################
# NGINX
###############################################################################
  nginx:
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
        tag: '{{.Name}}/{{.ID}}'
      #   syslog-facility: 'daemon'
    depends_on:
      - kibana
###############################################################################
# RabbitMQ
###############################################################################
  # Don't need RabbitMQ for now
  # rabbitmq:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
###############################################################################
# Authenticator
###############################################################################
  authenticator:
    build:
      context: ./authenticator
      dockerfile: Dockerfile
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
        tag: '{{.Name}}/{{.ID}}'
    depends_on:
      - redis
      - mongo
      - kibana
###############################################################################
# PDFGenerator
###############################################################################
  pdfgenerator:
    build:
      context: ./pdfgenerator
      dockerfile: Dockerfile
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
        tag: '{{.Name}}/{{.ID}}'
    depends_on:
      - mongo
      - kibana
###############################################################################
# Emailer
###############################################################################
  emailer:
    build:
      context: ./emailer
      dockerfile: Dockerfile
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
        tag: '{{.Name}}/{{.ID}}'
    depends_on:
      - mongo
      - pdfgenerator
      - kibana
###############################################################################
# Loca (Front/Back-end)
###############################################################################
  loca:
    build:
      context: ./loca
      dockerfile: Dockerfile
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
        tag: '{{.Name}}/{{.ID}}'
    depends_on:
      - mongo
      - emailer
      - kibana
