version: "3.3"
services:
  ###############################################################################
  # Redis
  ###############################################################################
  # redis:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
  ###############################################################################
  # Mongo
  ###############################################################################
  # mongo:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
  ###############################################################################
  # NGINX
  ###############################################################################
  # nginx:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
  ###############################################################################
  # RabbitMQ
  ###############################################################################
  # Don't need RabbitMQ for now
  # rabbitmq:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    build:
      context: ./services/authenticator
      dockerfile: Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # PDFGenerator
  ###############################################################################
  pdfgenerator:
    build:
      context: ./services/pdfgenerator
      dockerfile: Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    build:
      context: ./services/emailer
      dockerfile: Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # api
  ###############################################################################
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # Frontend
  ###############################################################################
  frontend:
    build:
      context: ./webapps/landlord
      dockerfile: Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
