version: '3.3'
services:
###############################################################################
# Vault
###############################################################################
  vault:
    volumes:
      - ./config/vault/dev.json:/vault/config/vault.json
###############################################################################
# NGINX
###############################################################################
  nginx:
    volumes:
      - ./config/nginx/etc/conf.d/dev.conf:/etc/nginx/conf.d/default.template
###############################################################################
# Authenticator
###############################################################################
  authenticator:
    build:
      context: ./authenticator
      dockerfile: dev.Dockerfile
    volumes:
      - ./authenticator:/usr/app
      - /usr/app/node_modules
    ports:
      - '$AUTHENTICATOR_DEBUG_PORT:9226'
###############################################################################
# PDFGenerator
###############################################################################
  pdfgenerator:
    build:
      context: ./pdfgenerator
      dockerfile: dev.Dockerfile
    volumes:
      - ./pdfgenerator:/usr/app
      - /usr/app/node_modules
    ports:
      - '$PDFGENERATOR_DEBUG_PORT:9227'
###############################################################################
# Emailer
###############################################################################
  emailer:
    build:
      context: ./emailer
      dockerfile: dev.Dockerfile
    volumes:
      - ./emailer:/usr/app
      - /usr/app/node_modules
    ports:
      - '$EMAILER_DEBUG_PORT:9228'
###############################################################################
# Loca (Front/Back-end)
###############################################################################
  loca:
    build:
      context: ./loca
      dockerfile: dev.Dockerfile
    volumes:
      - ./loca:/usr/app
      - /usr/app/node_modules
    ports:
      - '$LOCA_BACKEND_DEBUG_PORT:9229'
      - '$LOCA_BROWSER_SYNC_UI_PORT:3001'
###############################################################################
# Frontend
###############################################################################
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
      - /usr/app/public
