version: '3.3'
services:
###############################################################################
# Redis
###############################################################################
  redis:
    image: redis:5
    expose:
      - '$REDIS_PORT'
    volumes:
      - './data/redis:/data'
    command:
      - 'bash'
      - '-c'
      - 'docker-entrypoint.sh --requirepass $AUTHENTICATOR_TOKEN_DB_PASSWORD'
    networks:
      - net
###############################################################################
# Mongo
###############################################################################
  mongo:
    image: mongo:3.6
    expose:
      - '$MONGO_PORT'
    volumes:
      - './data/mongodb:/data/db'
    networks:
      - net
###############################################################################
# NGINX
###############################################################################
  nginx:
    image: nginx:1.17
    volumes:
      - ./config/nginx/etc/conf.d/prod.conf:/etc/nginx/conf.d/default.template
    ports:
      - '$NGINX_PORT:$NGINX_PORT'
    environment:
      - FRONTEND_PORT=$FRONTEND_PORT
      - LOCA_PORT=$LOCA_PORT
      - AUTHENTICATOR_PORT=$AUTHENTICATOR_PORT
      - NGINX_PORT=$NGINX_PORT
    command:
      - 'bin/bash'
      - '-c'
      - "envsubst '$${NGINX_PORT},$${LOCA_PORT},$${AUTHENTICATOR_PORT},$${FRONTEND_PORT}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - net
    depends_on:
      - loca
      - frontend
###############################################################################
# RabbitMQ
###############################################################################
  # Don't need RabbitMQ for now
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   hostname: 'rabbitmq'
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
  #     - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS
  #   expose:
  #     - '$RABBITMQ_PORT'
  #   ports:
  #     - '$RABBITMQ_MANAGEMENT_PORT:15672'
  #   labels:
  #     NAME: "rabbitmq1"
  #   networks:
  #     - net
###############################################################################
# Authenticator
###############################################################################
  authenticator:
    image: mre/authenticator:latest
    environment:
      - NODE_ENV
      - PORT=$AUTHENTICATOR_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - TOKEN_DB_URL=$AUTHENTICATOR_TOKEN_DB_URL
      - TOKEN_DB_PASSWORD=$AUTHENTICATOR_TOKEN_DB_PASSWORD
      - ACCESS_TOKEN_SECRET=$AUTHENTICATOR_ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET=$AUTHENTICATOR_REFRESH_TOKEN_SECRET
      - RESET_TOKEN_SECRET=$AUTHENTICATOR_RESET_TOKEN_SECRET
      - BASE_DB_URL=$BASE_DB_URL
      - EMAILER_URL=$EMAILER_URL
    expose:
      - '$AUTHENTICATOR_PORT'
    networks:
      - net
    depends_on:
      - redis
      - mongo
      - emailer
###############################################################################
# PDFGenerator
###############################################################################
  pdfgenerator:
    image: mre/pdfgenerator:latest
    environment:
      - NODE_ENV
      - PORT=$PDFGENERATOR_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - PRODUCTIVE=$PRODUCTIVE
      - BASE_DB_URL=$BASE_DB_URL
      - DB_URL=$PDFGENERATOR_DB_URL
    expose:
      - '$PDFGENERATOR_PORT'
    networks:
      - net
    depends_on:
      - mongo
###############################################################################
# Emailer
###############################################################################
  emailer:
    image: mre/emailer:latest
    environment:
      - NODE_ENV
      - PORT=$EMAILER_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - PRODUCTIVE=$PRODUCTIVE
      - BASE_DB_URL=$BASE_DB_URL
      - DB_URL=$EMAILER_DB_URL
      - PDFGENERATOR_URL=$PDFGENERATOR_URL
      - MAILGUN_API_KEY=$MAILGUN_API_KEY
      - MAILGUN_DOMAIN=$MAILGUN_DOMAIN
      - EMAIL_FROM=$EMAIL_FROM
      - EMAIL_REPLY_TO=$EMAIL_REPLY_TO
      - EMAIL_BCC=$EMAIL_BCC
    expose:
      - '$EMAILER_PORT'
    networks:
      - net
    depends_on:
      - mongo
      - pdfgenerator
###############################################################################
# Loca (Front/Back-end)
###############################################################################
  loca:
    image: mre/loca:latest
    environment:
      - NODE_ENV
      - NGINX_PORT=$NGINX_PORT
      - PORT=$LOCA_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - PRODUCTIVE=$PRODUCTIVE
      - BASE_DB_URL=$BASE_DB_URL
      - CONFIG_DIR=$CONFIG_DIR
      - DEMO_MODE=$DEMO_MODE
      - EMAILER_URL=$EMAILER_URL
      - RESTORE_DB=$RESTORE_DB
    expose:
      - '$LOCA_PORT'
    networks:
      - net
    depends_on:
      - mongo
      - authenticator
      - emailer
###############################################################################
# Frontend
###############################################################################
  frontend:
    image: mre/frontend:latest
    environment:
      - NODE_ENV
      - PORT=$FRONTEND_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - APP_NAME=$APP_NAME
      - API_URL=$API_URL
    expose:
      - '$FRONTEND_PORT'
    networks:
      - net
    depends_on:
      - loca
      - authenticator
  ###############################################################################
# microservices network
###############################################################################
networks:
  net:
    driver: bridge