version: '3.3'
services:
###############################################################################
# PDFGenerator
###############################################################################
  pdfgenerator:
    build: ../pdfgenerator
###############################################################################
# Emailer
###############################################################################
  emailer:
    build: ../emailer
###############################################################################
# Loca (Front/Back-end)
###############################################################################
  loca:
    build: ../loca

