version: '3.3'
services:
###############################################################################
# PDFGenerator
###############################################################################
  pdfgenerator:
    build:
      context: ./pdfgenerator
      dockerfile: dev.Dockerfile
    volumes:
      - ./pdfgenerator:/usr/app
      - /usr/app/node_modules
    ports:
      - '$PDFGENERATOR_DEBUG_PORT:9227'
###############################################################################
# Emailer
###############################################################################
  emailer:
    build:
      context: ./emailer
      dockerfile: dev.Dockerfile
    volumes:
      - ./emailer:/usr/app
      - /usr/app/node_modules
    ports:
      - '$EMAILER_DEBUG_PORT:9228'
###############################################################################
# Loca (Front/Back-end)
###############################################################################
  loca:
    build:
      context: ./loca
      dockerfile: dev.Dockerfile
    volumes:
      - ./loca:/usr/app
      - /usr/app/node_modules
    ports:
      - '$LOCA_BACKEND_DEBUG_PORT:9229'
      - '$LOCA_BROWSER_SYNC_UI_PORT:3001'
