version: '3.3'
services:
###############################################################################
# zookeeper
###############################################################################
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '$ZOOKEEPER_PORT'
    networks:
      - net
    logging:
      driver: 'syslog'
      options:
        tag: '{{.Name}}/{{.ID}}'
        syslog-facility: 'daemon'
        syslog-address: 'udp://localhost:$LOGSTASH_PORT'
###############################################################################
# kafka
###############################################################################
  kafka:
    image: wurstmeister/kafka
    ports:
      - '$KAFKA_PORT'
    networks:
      - net
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:$ZOOKEEPER_PORT'
    logging:
      driver: 'syslog'
      options:
        tag: '{{.Name}}/{{.ID}}'
        syslog-facility: 'daemon'
        syslog-address: 'udp://localhost:$LOGSTASH_PORT'
    depends_on:
      - zookeeper
networks:
  net:
    driver: bridge