version: "3.3"
services:
  nginx:
    environment:
      - RESETSERVICE_PORT=$RESETSERVICE_PORT
  resetservice:
    build:
      context: ./services/resetservice
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV
      - PORT=$RESETSERVICE_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - TOKEN_DB_URL=$AUTHENTICATOR_TOKEN_DB_URL
      - TOKEN_DB_PASSWORD=$AUTHENTICATOR_TOKEN_DB_PASSWORD
      - MONGO_URL=$BASE_DB_URL
    volumes:
      - ./services/resetservice:/usr/app
      - /usr/app/node_modules
    expose:
      - "$RESETSERVICE_PORT"
    ports:
      - "$RESETSERVICE_DEBUG_PORT:9225"
    networks:
      - net
    depends_on:
      - redis
      - mongo
